### ISSUE TITLE
installed RDM module asks for "passphrase" when attempting a command

### ISSUE THREAD

**Issue by Andre4041** [Devolutions/RDMSamples-ps#45]
everytime I try a command I get a "Please enter the passphrase". I dont remember setting a "passphrase" in RDM. I did set an application password but that doesnt seem to work. It also appears that I can enter past this enough and it will attempt the command, but it seems to error. What is this passphrase? I just installed ps 7 and the module and did not make any changes.

![image](https://github.com/Devolutions/RDMSamples-ps/assets/76021150/7159ef8c-803d-4d57-9f8b-a103207287d8)

**Comment by erica-poirier** [comment]
Hello,

We apologize for this delayed reply.

Do you still get the passphrase prompt?

What data source type are you using with the PowerShell module?

Best regards,

**Comment by erica-poirier** [comment]
Hello,

Since we did not get any reply, I'm closing this request. Feel free to reply to this message if the issue still exist.

Best regards,
